name: CI
on:
  push: { branches: [master] }
  pull_request: { branches: [master] }
  schedule: [ cron: '2 2 * * 6' ]  # Every Saturday, 02:02

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - run: pip install flake8 mypy
      - run: flake8 backtesting setup.py
      - run: mypy --no-warn-unused-ignores backtesting

  coverage:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -U --pre bokeh pandas numpy coverage && pip install -U .[test]
      - env: { BOKEH_BROWSER: none }
        run: time coverage run -m backtesting.test
      - run: coverage combine && coverage report

  build:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v4
      - run: pip install -U .[test]
      - env: { BOKEH_BROWSER: none }
        run: time python -m backtesting.test

  docs:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 3
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: pip install -e .[doc,test]  # -e provides ./backtesting/_version.py for pdoc
      - run: time doc/build.sh

  win64:
    needs:
      - build
      - docs
    runs-on: windows-latest
    timeout-minutes: 4
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - run: pip install .[test]
      - env: { BOKEH_BROWSER: none }
        run: python -m backtesting.test
