name: Deploy docs
on:
  push:
    tags: ['[0-9]+.[0-9]+.*']

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 3
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - run: pip install -U pip setuptools wheel
      - run: pip install -U -e .[doc,test]

      - run: time doc/build.sh

      - run: .github/deploy-gh-pages.sh
        env:
          GH_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
